### ISSUE TITLE
issue when do pip install image-prep

### ISSUE THREAD

**Issue by firefly2000** [F5Networks/f5-openstack-image-prep#47]
Run into issue when try following command and error messages as following: 

sudo pip install git:https://github.com/F5Networks/f5-openstack-image-prep

Collecting git:https://github.com/F5Networks/f5-openstack-image-prep
Exception:
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/pip/basecommand.py", line 215, in main
    status = self.run(options, args)
  File "/usr/lib/python2.7/site-packages/pip/commands/install.py", line 324, in run
    requirement_set.prepare_files(finder)
  File "/usr/lib/python2.7/site-packages/pip/req/req_set.py", line 380, in prepare_files
    ignore_dependencies=self.ignore_dependencies))
  File "/usr/lib/python2.7/site-packages/pip/req/req_set.py", line 620, in _prepare_file
    session=self.session, hashes=hashes)
  File "/usr/lib/python2.7/site-packages/pip/download.py", line 805, in unpack_url
    unpack_vcs_link(link, location)
  File "/usr/lib/python2.7/site-packages/pip/download.py", line 479, in unpack_vcs_link
    vcs_backend.unpack(location)
  File "/usr/lib/python2.7/site-packages/pip/vcs/__init__.py", line 286, in unpack
    self.obtain(location)
  File "/usr/lib/python2.7/site-packages/pip/vcs/git.py", line 131, in obtain
    url, rev = self.get_url_rev()
  File "/usr/lib/python2.7/site-packages/pip/vcs/git.py", line 272, in get_url_rev
    url, rev = super(Git, self).get_url_rev()
  File "/usr/lib/python2.7/site-packages/pip/vcs/__init__.py", line 138, in get_url_rev
    assert '+' in self.url, error_message % self.url
AssertionError: Sorry, 'git:https://github.com/F5Networks/f5-openstack-image-prep' is a malformed VCS url. The format is <vcs>+<protocol>://<url>, e.g. svn+http://myrepo/svn/MyApp#egg=MyApp

Thank you for all the help! - Haitao

**Comment by pjbreaux** [comment]
@firefly2000: check the new Readme file to be able to pip install. Also, your original command should be something like
`sudo pip install git+https://github.com/F5Networks/f5-openstack-image-prep`

**Comment by firefly2000** [comment]
Thank you! That works!

**Comment by pjbreaux** [comment]
Excellent.
